### ISSUE TITLE
Galleri-visningen ser ikke bra ut

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMidebank#2]
Tom Andreas har lagt til et bilde-galleri, som nå ser veldig rart ut. Vi hadde lignende feil i høst, og jeg trodde det var rettet. 
https://github.com/UKMNorge/UKMresources/commit/2f4a6893703df16c5e27422c3a12780fe9b99a24

Denne må vi finne utav :)

**Comment by kimduo** [comment]
**PR:** Remove overlapped image problem #3 [https://github.com/UKMNorge/UKMwp_innhold/pull/3]
